[package]
name         = "taplo-wasm"
version      = { workspace = true }
publish      = false
rust-version = { workspace = true }
authors      = { workspace = true }
edition      = { workspace = true }
homepage     = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
taplo-lsp-async = { workspace = true, optional = true }
taplo          = { workspace = true, features = ["serde"] }
taplo-cli      = { workspace = true, optional = true, default-features = false }
taplo-common   = { workspace = true, default-features = false, features = ["schema", "reqwest"] }
taplo-lsp      = { workspace = true, optional = true, default-features = false }

clap                     = { workspace = true, features = ["derive"], optional = true }
console_error_panic_hook = { workspace = true }
futures                  = { workspace = true }
serde                    = { workspace = true, features = ["derive"] }
serde-wasm-bindgen       = { workspace = true }
time                     = { workspace = true, features = ["parsing"] }
tokio                    = { workspace = true }
tracing                  = { workspace = true, optional = true }
thiserror                = { workspace = true }
url                      = { workspace = true }

# Bump all together since it's a monorepo
js-sys               = { workspace = true }
wasm-bindgen         = { workspace = true }
wasm-bindgen-futures = { workspace = true }

[features]
default = ["cli", "lsp"]
cli     = ["dep:clap", "dep:taplo-cli", "dep:tracing"]
lsp     = ["dep:taplo-lsp-async", "dep:taplo-lsp"]
