[package]
name         = "taplo"
description  = "A TOML parser, analyzer and formatter library"
version      = { workspace = true }
rust-version = { workspace = true }
categories   = ["parser-implementations", "parsing"]
keywords     = ["toml", "parser", "formatter", "linter"]
readme       = "../../README.md"
authors      = { workspace = true }
edition = { workspace = true }
homepage     = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[features]
default = ["serde"]
schema  = ["schemars"]

[dependencies]
globset    = { workspace = true }
itertools  = { workspace = true }
logos      = { workspace = true }
rowan      = { workspace = true }
serde_json = { workspace = true }
thiserror  = { workspace = true }
time       = { workspace = true, features = ["parsing", "formatting", "macros"] }

schemars = { workspace = true, optional = true }
serde    = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
criterion        = { workspace = true }   # criterion -> clap
proptest         = { workspace = true }
serde_json       = { workspace = true }
strict-test-support = { workspace = true }
toml             = { workspace = true }

[target.'cfg(unix)'.dev-dependencies]
pprof = { workspace = true, features = ["flamegraph", "criterion"] } # pprof -> criterion -> clap

[package.metadata.docs.rs]
features = ["serde", "schema"]

[package.metadata.auto-tag]
enabled = true

[[bench]]
harness = false
name    = "taplo"

[[bench]]
harness = false
name    = "profile"
